spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User-login-system?createDatabaseIfNotExist=true
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

server:
  port: 8080

